### PR TITLE
Expanded Event Status

### PR DESCRIPTION
**Pull request by avihut**
Added status summary to the event status fragment.

screen shot 2015-03-16 at 01 15 50

### CODE REVIEW

**Comment by ShayDavidson** [comment]
Everything is awesome!

**Comment by ShayDavidson** [comment]
btw, doesn't this suppose to be opened against your other branch?

**Comment by avihut** [comment]
Yeah, it should have been opened against my previous branch. Sorry for that :/
Now I can't change it...

**Comment by ShayDavidson** [comment]
doesn't really matter, just merge this and close the other :)

**Comment by avihut** [comment]
I'm still waiting for Benny to go over it

**Pull request closed without merging**
